// frontend/src/PipelineStatus.svelte
<script>
import SyncLoader from './SyncLoader.svelte'

export let submitid;
let job_status = '';
let message = '';

async function update() {
    const res = await fetch(`/submit/${submitid}/pipeline`);
    const json = await res.json();

    if(json.finished) {
        document.location.reload();
    } else {
        job_status = json['status'];
        message = json['message'];
        setTimeout(update, 1000);
    }
}

update();
</script>

<style>
    div.main {
        font-size: 1.5rem;
        font-weight: bold;
        text-align: center;
    }
</style>

{#if job_status == 'failed'}
  <h2 class="text-danger text-center"><b>Evaluation failed - please contact your teacher.</b></h2>

  <pre>{message}</pre>
{:else}
  <div class="main">
    Your submit is being processed, please wait.<br />
    Your submit has been uploaded to Kelvin, it won't be lost if you close the browser.<br />
    {job_status}
    <div class="d-flex justify-content-center">
        <SyncLoader />
    </div>
  </div>
{/if}

// frontend/src/components/PipelineStatus.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import SyncLoader from './SyncLoader.vue';
import { getFromAPI } from '../utilities/api';

const props = defineProps<{
  submitid: string | number;
}>();

const jobStatus = ref('');
const message = ref('');
let timer: ReturnType<typeof setTimeout> | undefined;

async function update() {
  const json = await getFromAPI<{ finished: boolean; status: string; message: string }>(
    `/submit/${props.submitid}/pipeline`
  );

  if (!json) {
    // Transient failure - keep polling.
    timer = setTimeout(update, 1000);
    return;
  }

  if (json.finished) {
    document.location.reload();
    return;
  }

  jobStatus.value = json.status;
  message.value = json.message;

  // A failed evaluation is terminal - show the message and stop polling.
  if (json.status !== 'failed') {
    timer = setTimeout(update, 1000);
  }
}

onMounted(update);
onUnmounted(() => clearTimeout(timer));
</script>

<template>
  <template v-if="jobStatus === 'failed'">
    <h2 class="text-danger text-center">
      <b>Evaluation failed - please contact your teacher.</b>
    </h2>
    <pre>{{ message }}</pre>
  </template>
  <div v-else class="main">
    Your submit is being processed, please wait.<br />
    Your submit has been uploaded to Kelvin, it won't be lost if you close the browser.<br />
    {{ jobStatus }}
    <div class="d-flex justify-content-center">
      <SyncLoader />
    </div>
  </div>
</template>

<style scoped>
div.main {
  font-size: 1.5rem;
  font-weight: bold;
  text-align: center;
}
</style>
