// frontend/src/Tests.svelte
<style>
    :global(.tests .CodeMirror) {
      height: 200px !important;
      min-height: 200px !important;
    }
</style>
    

<script>
    import yaml from 'js-yaml';
    import {fs, cwd, openedFiles, currentOpenedFile} from './fs.js'
    import Editor from './Editor.svelte'
    import SyncLoader from './SyncLoader.svelte'

    let loaded = false;
    $: tests = {};

    function create(name) {
        return {
            'name': name,
            'args': '',
            'files': {},
        }
    }

    function add_test() {
        const name = `test${Object.keys(tests).length}`
        tests[name] = create(name);
    }

    async function delete_test(name) {
        const filesToDelete = tests[name]['files'];

        delete tests[name];
        tests = tests;

        for(const path of Object.values(filesToDelete)) {
            await fs.remove(path);
        }

        currentOpenedFile.update(current => {return null});
    }

    async function add_file(name, shown_name, file_name) {
        const path = `${name}.${file_name}`
        await fs.createFile(path);
        await fs.open(path, {'hide_tab': true});
        tests[name]['files'][shown_name] = '/' + path;
    }

    async function remove_file(name, file_name) {
        const path = tests[name]['files'][file_name];
        delete tests[name]['files'][file_name];
        tests = tests;
        await fs.remove(path);
        currentOpenedFile.update(current => {return null});
    }

    async function load() {
        let newtests = {};

        if(await fs.open('tests.yml', {'hide_tab': true})) {
            const descs = yaml.load($openedFiles['/tests.yml'].content);

            if(Array.isArray(descs)) {
                for(const test of descs) {
                    if(test.name) {
                        newtests[test.name] = newtests[test.name] || create(test.name);
                        if(test.args) {
                            newtests[test.name].args = test.args.join(' ')
                        }
                        newtests[test.name].title = test.title;
                        newtests[test.name].exit_code = test.exit_code;
                    }
                }
            }
        }

        for(const inode of $cwd) {
            if(inode.type != 'file') {
                continue;
            }

            async function add(name, x, file_name) {
                let test = newtests[name] = newtests[name] || create(name);
                test['files'][x] = '/' + file_name;
                await fs.open(file_name, {'hide_tab': true});
            }

            const parts = inode.name.split('.');
            const ext = parts[parts.length - 1];
            const name = parts[0];
            if(ext == 'out' || ext == 'in' || ext == 'err' && parts.length == 2) {
                await add(name, 'std' + parts[1], inode.name)
            } else if(parts.length >= 3) {
                const dir = parts[1];
                if(dir == 'file_in' || dir == 'file_out') {
                    await add(name, parts.slice(2).join('.'), inode.name);
                }
            }
        }


        tests = newtests;
        loaded = true;
    }

    $: if(loaded) {
        save(tests);
    }

    async function save(tests) {
        let description = [];
        for(const [name, test] of Object.entries(tests)) {
            let data = {};
            if(test.args) {
                data.args = test.args.split(' ');
            }

            if(test.title) {
                data.title = test.title;
            }

            if(test.exit_code) {
                data.exit_code = parseInt(test.exit_code); 
            }

            if(data) {
                description.push({name: name, ...data});
            }
        }

        if(!await fs.open('tests.yml', {hide_tab: true})) {
            await fs.createFile('tests.yml');
            await fs.open('tests.yml', {hide_tab: true});
        }
        $openedFiles['/tests.yml'].content = yaml.dump(description);
    }

    function file_sorter(a, b) {
        const stds = ['stdin', 'stdout', 'stderr'];
        const isStd = name => stds.indexOf(name) != -1;

        a = a[0];
        b = b[0];

        if(isStd(a) && isStd(b)) {
            return stds.indexOf(a) < stds.indexOf(b) ? -1 : 1;
        }
        
        if(isStd(a)) {
            return -1;
        }

        return 1;
    }

    load();
</script>

{#if loaded}
<div class="tests ps-3">
{#each Object.values(tests) as test}
    <h2>
        {test.name}

        {#each ['stdin', 'stdout', 'stderr'] as fd}
            {#if !test.files[fd]}
                <button on:click={add_file(test.name, fd, fd.replace('std', ''))} class="btn btn-sm btn-success me-1">
                    <span class="iconify" data-icon="ant-design:plus-outlined"></span>
                    {fd}
                </button>
            {/if}
        {/each}

        <div class="btn-group" role="group" aria-label="Basic example">
            <input type="text" class="form-control form-control-sm" placeholder="Filename" bind:value={test.new_filename}>
        
            <button type="button" class="btn btn-sm btn-success text-nowrap" on:click={() => test.new_filename && add_file(test.name, test.new_filename, `file_in.${test.new_filename}`)}><span class="iconify" data-icon="ant-design:plus-outlined"></span>input</button>
            <button type="button" class="btn btn-sm btn-success text-nowrap" on:click={() => test.new_filename && add_file(test.name, test.new_filename, `file_out.${test.new_filename}`)}><span class="iconify" data-icon="ant-design:plus-outlined"></span>output</button>
        </div>

        <button class="btn btn-sm btn-danger" on:click={() => delete_test(test.name)}>
            <span class="iconify" data-icon="humbleicons:times"></span>
        </button>
    </h2>

    <div class="row mb-0">
        <label class="col-sm-2 col-form-label">Title</label>
        <input type="text" class="form-control form-control-sm col-sm-10" bind:value={test.title}>
    </div>

    <div class="row mb-0">
        <label class="col-sm-2 col-form-label">Program Arguments</label>
        <input type="text" class="form-control form-control-sm col-sm-10" bind:value={test.args}>
    </div>

    <div class="row mb-0">
        <label class="col-sm-2 col-form-label">Exit code</label>
        <input type="number" class="form-control form-control-sm col-sm-10" bind:value={test.exit_code} placeholder="Default 0">
    </div>

    {#each Object.entries(test.files).sort(file_sorter) as [k, v]}
        <h3>
            {k}
            <button on:click={() => remove_file(test.name, k)} class="btn btn-sm btn-danger">
                <span class="iconify" data-icon="humbleicons:times"></span>
            </button>
        </h3>
        <Editor bind:value={$openedFiles[v].content} />
    {/each}


    <hr>
{/each}
<button on:click={add_test} class="btn btn-success">
    <span class="iconify" data-icon="ant-design:plus-outlined"></span>
    Add new test
</button>

</div>
{:else}
    <div class="d-flex justify-content-center">
        <SyncLoader />
    </div>
{/if}

// frontend/src/Teacher/EditTask/Tests.vue
<script setup lang="ts">
/**
 * Component for test management
 *  - shows list of loaded tests
 *  - allow to modify them and automatically sync changes to tests.yml file
 */

import { ref, watch, reactive } from 'vue';
import Editor from '../../components/Editor.vue';
import SyncLoader from '../../components/SyncLoader.vue';
import yaml from 'js-yaml';
import { currentOpenedFile, fs, cwd, openedFiles } from '../../fs.js';

//indicates whether the tests have been loaded
const loaded = ref<boolean>(false);

interface Test {
  /** autogenerated name in format 'test0' */
  name: string;

  /** user defined name of test */
  title?: string;

  /** arguments passed to the tested program */
  args?: string;

  /** input/output files */
  files?: Record<string, string>;

  /** expected exit code */
  exit_code?: number;
}

let tests = reactive<Record<string, Test>>({});

//used in form, name for input/output file to be created
const new_test_io_file = reactive<Record<string, string>>({});

/**
 * Returns empty test with given name.
 * Used both to load old tests and create new ones
 *
 * @param name name in format `test0`
 */
function create(name: string): Test {
  return {
    name: name,
    files: reactive<Record<string, string>>({})
  };
}

/**
 * Creates new test, with index last_test + 1
 */
function add_test() {
  const name = `test${Object.keys(tests).length}`;
  tests[name] = create(name);
}

/**
 * Removes test of given name and all associated input/output files
 * @param name tame of test to delete
 */
async function delete_test(name: string): Promise<void> {
  const filesToDelete = tests[name]['files'];

  delete tests[name];

  for (const path of Object.values(filesToDelete)) {
    await fs.remove(path);
  }

  currentOpenedFile.value = null;
}

/**
 * Creates a new IO file and attaches it to the test
 * @param name test name
 * @param shown_name name of file showed to user (e.g. file1)
 * @param file_name name of file in FS (e.g. test0.file_in.file1)
 */
async function add_file(name: string, shown_name: string, file_name: string): Promise<void> {
  const path = `${name}.${file_name}`;
  await fs.createFile(path);
  await fs.open(path, { hide_tab: true });
  tests[name]['files'][shown_name] = '/' + path;
}

/**
 * Removes one IO file
 * @param name test to which the file belongs
 * @param file_name name of IO file
 */
async function remove_file(name: string, file_name: string): Promise<void> {
  const path = tests[name]['files'][file_name];
  delete tests[name]['files'][file_name];
  await fs.remove(path);

  currentOpenedFile.value = null;
}

/**
 * Creates a new IO file and attaches it to the test
 * @param test test object
 * @param shown_name name of file showed to user (e.g. file1)
 * @param file_name name of file in FS (e.g. test0.file_in.file1)
 */
async function add_file_to_test(test: Test, shown_name: string, file_name: string): Promise<void> {
  test['files'][shown_name] = '/' + file_name;
  await fs.open(file_name, { hide_tab: true });
}

interface YamlTestRecord {
  name: string;
  title?: string;
  args?: string[];
  exit_code?: number;
}

/**
 * Load all tests from 'tests.yml' file and all associated IO files
 */
async function load() {
  let new_tests: Record<string, Test> = {};

  if (await fs.open('tests.yml', { hide_tab: true })) {
    const descs: YamlTestRecord[] = yaml.load(openedFiles.value['/tests.yml'].content);

    if (Array.isArray(descs)) {
      for (const test of descs) {
        if (test.name) {
          new_tests[test.name] = new_tests[test.name] || create(test.name);
          if (test.args) {
            new_tests[test.name].args = test.args.join(' ');
          }
          new_tests[test.name].title = test.title;
          new_tests[test.name].exit_code = test.exit_code;
        }
      }
    }
  }

  for (const inode of cwd.value) {
    if (inode.type != 'file') {
      continue;
    }

    const parts = inode.name.split('.');
    const ext = parts[parts.length - 1];
    const name = parts[0];
    if (ext == 'out' || ext == 'in' || (ext == 'err' && parts.length == 2)) {
      new_tests[name] = new_tests[name] || create(name);
      await add_file_to_test(new_tests[name], 'std' + parts[1], inode.name);
    } else if (parts.length >= 3) {
      const dir = parts[1];
      if (dir == 'file_in' || dir == 'file_out') {
        new_tests[name] = new_tests[name] || create(name);
        await add_file_to_test(new_tests[name], parts.slice(2).join('.'), inode.name);
      }
    }
  }

  Object.assign(tests, new_tests);
  loaded.value = true;
}

watch(
  tests,
  () => {
    if (loaded.value) save(tests);
  },
  { deep: true }
);

async function save(tests: Record<string, Test>) {
  let description: Array<YamlTestRecord> = [];
  for (const [name, test] of Object.entries(tests)) {
    let data: YamlTestRecord = { name: name };
    if (test.args) {
      data.args = test.args.split(' ');
    }

    if (test.title) {
      data.title = test.title;
    }

    if (test.exit_code) {
      data.exit_code = test.exit_code;
    }

    if (data) {
      description.push(data);
    }
  }

  if (!(await fs.open('tests.yml', { hide_tab: true }))) {
    await fs.createFile('tests.yml');
    await fs.open('tests.yml', { hide_tab: true });
  }
  openedFiles.value['/tests.yml'].content = yaml.dump(description);
}

function file_sorter(a: [string, string], b: [string, string]): number {
  const stds = ['stdin', 'stdout', 'stderr'];
  const isStd = (name: string) => stds.indexOf(name) != -1;

  let a_key: string = a[0];
  let b_key: string = b[0];

  if (isStd(a_key) && isStd(b_key)) {
    return stds.indexOf(a_key) < stds.indexOf(b_key) ? -1 : 1;
  }

  if (isStd(a_key)) {
    return -1;
  }

  return 1;
}

load();
</script>

<template>
  <div v-if="loaded" class="tests ps-3">
    <div v-for="(test, name) in tests" :key="name">
      <h2>
        {{ test.name }}

        <span v-for="fd in ['stdin', 'stdout', 'stderr']" :key="fd">
          <button
            v-if="!test.files[fd]"
            class="btn btn-sm btn-success me-1"
            @click="add_file(test.name, fd, fd.replace('std', ''))"
          >
            <span class="iconify" data-icon="ant-design:plus-outlined"></span>
            {{ fd }}
          </button>
        </span>

        <div class="btn-group" role="group" aria-label="Basic example">
          <input
            v-model="new_test_io_file[name]"
            type="text"
            class="form-control form-control-sm"
            placeholder="Filename"
          />

          <button
            type="button"
            class="btn btn-sm btn-success text-nowrap"
            @click="
              () => {
                if (new_test_io_file)
                  add_file(test.name, new_test_io_file[name], `file_in.${new_test_io_file[name]}`);
              }
            "
          >
            <span class="iconify" data-icon="ant-design:plus-outlined"></span>input
          </button>
          <button
            type="button"
            class="btn btn-sm btn-success text-nowrap"
            @click="
              () => {
                if (new_test_io_file[name])
                  add_file(
                    test.name,
                    new_test_io_file[name],
                    `file_out.${new_test_io_file[name]}}`
                  );
              }
            "
          >
            <span class="iconify" data-icon="ant-design:plus-outlined"></span>output
          </button>
        </div>
        &nbsp;
        <button class="btn btn-sm btn-danger" @click="delete_test(test.name)">
          <span class="iconify" data-icon="humbleicons:times"></span>
        </button>
      </h2>

      <div class="row mb-0">
        <label class="col-sm-2 col-form-label" for="title">Title</label>
        <input
          v-model="test.title"
          name="title"
          type="text"
          class="form-control form-control-sm col-sm-10"
        />
      </div>

      <div class="row mb-0">
        <label class="col-sm-2 col-form-label" for="args">Program Arguments</label>
        <input
          v-model="test.args"
          name="args"
          type="text"
          class="form-control form-control-sm col-sm-10"
        />
      </div>

      <div class="row mb-0">
        <label class="col-sm-2 col-form-label" for="exit-code">Exit code</label>
        <input
          v-model="test.exit_code"
          name="exit-code"
          type="number"
          class="form-control form-control-sm col-sm-10"
          placeholder="Default 0"
        />
      </div>

      <div v-for="[k, v] in Object.entries(test.files).sort(file_sorter)" :key="k">
        <h3>
          {{ k }}
          <button class="btn btn-sm btn-danger" @click="remove_file(test.name, k)">
            <span class="iconify" data-icon="humbleicons:times"></span>
          </button>
        </h3>
        <Editor v-model="openedFiles[v].content" :filename="currentOpenedFile" />
      </div>

      <hr />
    </div>
    <button class="btn btn-success" @click="add_test()">
      <span class="iconify" data-icon="ant-design:plus-outlined"></span>
      Add new test
    </button>
  </div>
  <div v-else class="d-flex justify-content-center">
    <SyncLoader />
  </div>
</template>

<style scoped>
:global(.tests .CodeMirror) {
  height: 200px !important;
  min-height: 200px !important;
}
</style>
