// frontend/src/ClassFilter.svelte
<script>
    import {fetch} from './api.js'
    import {user} from './global.js'
    import {push} from 'svelte-spa-router'

    let semesters = {};
    let teachers = [];
    let allTeachers = [];
    let classes = [];
    let allClasses = [];

    export let semester;
    export let subject;
    export let teacher;
    export let clazz;

    async function load() {
      const res = await fetch('/api/classes/all');
      const json = await res.json();
      semesters = json['semesters'];

      let allTeachersSet = new Set();
      let allClassesSet = new Set();
      for (const semester in semesters) {
        for (const subject in semesters[semester]) {
          for (const teacher in semesters[semester][subject]) {
            allTeachersSet.add(teacher);
            for (const class_code of semesters[semester][subject][teacher]) {
              allClassesSet.add(class_code);
            }
          }
        }
      }
      allTeachers = [...allTeachersSet];
      allClasses = [...allClassesSet];
    }

    function resetClass() {
        clazz = undefined;
    }

    function fillTeacher() {
      if(subject && semesters[semester][subject].hasOwnProperty($user.username) >= 0) {
        teacher = $user.username;
      }
      resetClass();
    }

    $: if(semesters) {
      let subjs = [];
      const sem = semesters[semester];
      if(sem) {
        for(const subj in sem) {
          if(sem[subj].hasOwnProperty($user.username) >= 0) {
            subjs.push(subj);
          }
        }
      }
    }

    $: {
        if(semesters && semesters[semester]) {
          if(!semesters[semester][subject]) {
            subject = null;
          } else if(semesters[semester][subject].hasOwnProperty(teacher) < 0) {
            teacher = null;
          }
        }

        const params = new URLSearchParams(Object.fromEntries(Object.entries({
            'semester': semester,
            'subject': subject,
            'teacher': teacher,
            'class': clazz,
        }).filter(([_, v]) => v)));
        push('/?' + params);
    }

    $: {
        if (semester && subject && semesters[semester]?.[subject]) {
          teachers = Object.keys(semesters[semester][subject]);
          if (teacher && semesters[semester]?.[subject]?.[teacher]) {
            classes = semesters[semester][subject][teacher];
          } else {
            let filteredClasses = [];
            for (const t in semesters[semester][subject]) {
                filteredClasses.push(...semesters[semester][subject][t]);
            }
            classes = filteredClasses;
          }
        } else {
          teachers = allTeachers;
          classes = allClasses;
        }
    }

    function sorted(items, compare_fn) {
      items.sort(compare_fn);
      return items;
    }

    function compare_semester(a, b) {
      let year_a = Number(a.substring(0, 4));
      let year_b = Number(b.substring(0, 4));
      if (year_a < year_b) {
        return -1;
      } else if (year_a > year_b) {
        return 1;
      } else {
        return a[4] === "W" ? -1 : 1;
      }
    }

    load();
</script>

<div class="ms-auto">
  <div class="input-group">
    <select class="form-select form-select-sm" bind:value={semester} on:change={resetClass}>
        <option value="">Semester</option>
        {#each sorted(Object.keys(semesters), compare_semester) as semester (semester)}
            <option>{semester}</option>
        {/each}
    </select>

    <select class="form-select form-select-sm" bind:value={subject} on:change={fillTeacher} disabled={!semester}>
        <option value="">Subject</option>
        {#if semesters && semesters[semester]}
            {#each sorted(Object.keys(semesters[semester])) as subj (subj)}
                <option>{subj}</option>
            {/each}
        {/if}
    </select>

    {#if $user.is_superuser}
      <select class="form-select form-select-sm" bind:value={teacher} on:change={resetClass}>
          <option value="">Teacher</option>
            {#each sorted(teachers) as teacher (teacher)}
                <option>{teacher}</option>
            {/each}
      </select>
    {/if}
    <select class="form-select form-select-sm" bind:value={clazz} disabled={!(semester && subject)}>
      <option value="">Class</option>
      <!-- `classes` are sorted serverside -->
      {#each classes as clazz (clazz)}
        <option>{clazz}</option>
      {/each}
    </select>
  </div>
</div>

// frontend/src/Teacher/ClassFilter.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue';
//import { useRouter } from 'vue-router';
import { getFromAPI } from '../utilities/api';
//import { user } from './global.js';
import { user } from '../utilities/global';
import { type ClassesByTeacher } from './frontendtypes';

//const user = ref({ username: 'GAU01', is_staff: true, is_superuser: true }); // FIXME: Get user from /api/info

//const router = useRouter();

const semesters = ref({});
const teachers = ref([]);
const allTeachers = ref([]);
const classes = ref([]);
const allClasses = ref([]);

const semester = ref('');
const subject = ref('');
const teacher = ref('');
const clazz = ref('');

async function load() {
  const res = await getFromAPI<{ semesters: ClassesByTeacher }>('/api/classes/all');
  //const json = await res.json();
  semesters.value = res.semesters; //json.semesters;

  const allTeachersSet = new Set();
  const allClassesSet = new Set();
  for (const sem in semesters.value) {
    for (const subj in semesters.value[sem]) {
      for (const t in semesters.value[sem][subj]) {
        allTeachersSet.add(t);
        for (const c of semesters.value[sem][subj][t]) {
          allClassesSet.add(c);
        }
      }
    }
  }
  allTeachers.value = [...allTeachersSet];
  allClasses.value = [...allClassesSet];
}

function resetClass() {
  clazz.value = '';
}

function fillTeacher() {
  if (
    subject.value &&
    semesters.value[semester.value]?.[subject.value]?.hasOwnProperty(user.value.username)
  ) {
    teacher.value = user.value.username;
  }
  resetClass();
}

function sorted(items, compareFn?) {
  return [...items].sort(compareFn);
}

function compareSemester(a, b) {
  const yearA = Number(a.substring(0, 4));
  const yearB = Number(b.substring(0, 4));
  if (yearA < yearB) return -1;
  if (yearA > yearB) return 1;
  return a[4] === 'W' ? -1 : 1;
}

watch([semester, subject, teacher, clazz], () => {
  const params = new URLSearchParams(
    Object.fromEntries(
      Object.entries({
        semester: semester.value,
        subject: subject.value,
        teacher: teacher.value,
        class: clazz.value
      }).filter(([, v]) => v)
    )
  );
  //router.push({ path: '/', query: Object.fromEntries(params.entries()) });
});

watch([semester, subject, teacher], () => {
  const sem = semesters.value[semester.value];
  if (!sem) return;

  if (subject.value && !sem[subject.value]) {
    subject.value = '';
  } else if (subject.value && teacher.value && !sem[subject.value]?.hasOwnProperty(teacher.value)) {
    teacher.value = '';
  }

  if (semester.value && subject.value && sem?.[subject.value]) {
    teachers.value = Object.keys(sem[subject.value]);
    if (teacher.value && sem[subject.value][teacher.value]) {
      classes.value = sem[subject.value][teacher.value];
    } else {
      const merged = [];
      for (const t in sem[subject.value]) {
        merged.push(...sem[subject.value][t]);
      }
      classes.value = merged;
    }
  } else {
    teachers.value = allTeachers.value;
    classes.value = allClasses.value;
  }
});

onMounted(load);
</script>

<template>
  <div class="ms-auto">
    <div class="input-group">
      <select v-model="semester" class="form-select form-select-sm" @change="resetClass">
        <option value="">Semester</option>
        <option v-for="s in sorted(Object.keys(semesters), compareSemester)" :key="s">
          {{ s }}
        </option>
      </select>

      <select
        v-model="subject"
        class="form-select form-select-sm"
        :disabled="!semester"
        @change="fillTeacher"
      >
        <option value="">Subject</option>
        <option v-for="subj in sorted(Object.keys(semesters[semester] || {}))" :key="subj">
          {{ subj }}
        </option>
      </select>

      <select
        v-if="user.is_superuser"
        v-model="teacher"
        class="form-select form-select-sm"
        @change="resetClass"
      >
        <option value="">Teacher</option>
        <option v-for="t in sorted(teachers)" :key="t">
          {{ t }}
        </option>
      </select>

      <select v-model="clazz" class="form-select form-select-sm" :disabled="!(semester && subject)">
        <option value="">Class</option>
        <option v-for="c in classes" :key="c">
          {{ c }}
        </option>
      </select>
    </div>
  </div>
</template>
