// frontend/src/TaskFilter.svelte
<script>
import { task_types } from './taskTypes.js';

export let task_type = null;

function setTaskType(type) {
  task_type = type;
}
</script>

<div class="ms-auto">
  <div class="input-group">
    {#each task_types as { key, value }}
      <button
        type="button"
        class="btn btn-dark {key == task_type ? 'active' : ''}"
        on:click={() => setTaskType(key)}
        on:change>{value}</button>
    {/each}
  </div>
</div>

// frontend/src/Teacher/TaskFilter.vue
<script setup lang="ts">
import { task_types } from '../taskTypes';
import { theme } from '../utilities/theme';

const taskType = defineModel<string | null>('taskType', { default: null });
</script>

<template>
  <div class="ms-auto">
    <div class="input-group">
      <button
        v-for="{ key, value } in task_types"
        :key="value"
        type="button"
        class="btn"
        :class="[`btn-${theme}`, { active: key === taskType }]"
        @click="taskType = key"
      >
        {{ value }}
      </button>
    </div>
  </div>
</template>
