// frontend/src/components/submit/CommentForm.vue
<script lang="ts" setup>
import { ref, watch } from 'vue';
import Editor from '../Editor.vue';

const props = withDefaults(
  defineProps<{
    comment?: string;
    disabled?: boolean;
  }>(),
  {
    comment: '',
    disabled: false
  }
);

const emit = defineEmits(['save']);

const localComment = ref(props.comment);

watch(
  () => props.comment,
  (value) => {
    localComment.value = value;
  }
);

const submit = () => {
  if (!props.disabled) {
    emit('save', localComment.value);
  }
};
</script>

<template>
  <Editor
    v-model:value="localComment"
    filename="comment.md"
    :disabled="disabled"
    :wrap="true"
    :autofocus="true"
    :extra-keys="{ 'Ctrl-Enter': submit }"
  />
  <button class="btn btn-sm btn-primary mt-1" :disabled="disabled" @click.prevent="submit">
    Add comment
  </button>
</template>

// frontend/src/CommentForm.svelte
<style>
:global(.comment .CodeMirror) {
  height: 100px;
}
</style>

<script>
    import { createEventDispatcher } from 'svelte';
    import Editor from './Editor.svelte'
    export let comment = '';
    export let disabled = false;

    const dispatch = createEventDispatcher();

  function submit() {
    if(!disabled) {
      dispatch('save', comment);
    }
  }
</script>

<Editor bind:value={comment} filename="comment.md" {disabled} wrap={true} autofocus extraKeys={{'Ctrl-Enter': submit}} />
<button class="btn btn-sm btn-primary mt-1" on:click|preventDefault={submit} {disabled}>Add comment</button>
