// web/static/notifications.vue
Vue.component('notifications', {
  props: ['url'],
  data() {
    return {
      unread_count: null,
      notifications: [],
			show: false,
    };
  },
  template: `
  <span style="position: relative">
    <span v-on:click="click" style="cursor: pointer">
      <img src="/static/notify_icon.png" style="height: 15px;" />
      <span class="badge badge-pill badge-danger" style="margin-left: -3px" v-if="unread_count > 0">{{ unread_count }}</span>
    </span>
    <div style="position: absolute; width: 300px; right: 0px; z-index: 2; background: whitesmoke;" v-if="show">
				<ul class="list-group">
					<li class="list-group-item" style="background-color: rgba(0,0,0,.03)">
						Notifications <span v-if="unread_count > 0">({{ unread_count }})</span>
						<span class="btn" class="float-right" style="cursor: pointer" v-on:click="markAllRead">&times;</span>
					</li>
					<div style="max-height: 300px; overflow-y: auto; font-size: 80%;">
            <template v-if="notifications.length > 0">
              <li v-for="(item, _) in notifications" class='list-group-item p-1' v-bind:class="{'list-group-item-light': !item.unread}">
                <strong v-if="item.actor_full_name">{{ item.actor_full_name }}</strong>
                <strong v-else>{{ item.actor }}</strong>
                {{ item.verb }} 

                <a :href="item.action_object_url" v-if="item.action_object_url">{{ item.action_object }}</a>
                <span v-else>{{ item.action_object }}</span>
                on 
                {{ item.target }}
              </li>
            </template>
            <li class="list-group-item p-1 text-center" v-else>There are no notifications!</span>
					</div>
				</ul>
    </div>
  </span>`,
  methods: {
    markAllRead() {
      axios.post('/notification/mark_as_read').then(() => {
        this.refresh();
      });
    },
    refresh() {
      axios.get('/notification/all').then((response) => {
        this.unread_count = response.data.unread_count;
        this.notifications = response.data.notifications;
      })
    },
    click() {
      this.show = !this.show; 
    },
  },
  mounted() {
		this.refresh();
//    setInterval(this.refresh, 5000);
  },
});

new Vue({
  el: '#notifications',
});

// frontend/src/Notifications.svelte
<script>
import {notifications, pushNotifications} from './notifications.js'
import TimeAgo from './TimeAgo.svelte'
import {clickOutside} from './utils'

let show = false;

async function enablePushNotifications() {
  if(!(await pushNotifications.subscribePushNotifications())) {
    alert('Notifications are denied, click on the icon before the URL address and enable them manually.');
  }
}

async function openNotification(notification) {
  if(notification.public) {
    await notifications.markRead(notification.id);
  }
  document.location.href = notification.action_object_url;
}

</script>

{#if $notifications}
<span style="position: relative" use:clickOutside on:click_outside={() => show = false}>
    <span on:click={() => show = !show} style="cursor: pointer">
      <img src="/static/notify_icon.png" style="height: 15px;" />
      {#if $notifications.unread_count > 0}
        <span class="badge badge-pill badge-danger" style="margin-left: -3px">{$notifications.unread_count}</span>
      {/if}
    </span>

    {#if show}
    <div style="position: absolute; width: 300px; right: 0px; z-index: 10; background: whitesmoke;">
				<ul class="list-group">
					<li class="list-group-item" style="background-color: rgba(0,0,0,.03)">
            Notifications {#if $notifications.unread_count > 0}({$notifications.unread_count}){/if}

            <div class="float-right">
              {#if $pushNotifications.supported && !$pushNotifications.enabled}
              <button class="btn p-0" title="Enable desktop notifications" on:click|preventDefault={enablePushNotifications}>
                <span class="iconify" data-icon="ic:outline-notifications-active"></span>
              </button>
              {/if}

              <button class="btn p-0" class:text-muted={$notifications.unread_count <= 0} on:click|preventDefault={notifications.markAllRead} title="Clear notifications">
                <span class="iconify" data-icon="mdi:notification-clear-all"></span>
              </button>
            </div>
					</li>
					<div style="max-height: 300px; overflow-y: auto; font-size: 80% !important;">
            {#if $notifications.notifications.length > 0}
              {#each $notifications.notifications as item}
              <li class='list-group-item p-1' class:list-group-item-light={!item.unread}>
                <div style="float: right">
                  <button class:invisible={!item.unread} class="btn p-0" on:click|preventDefault={() => notifications.markRead(item.id)}>&times;</button>
                </div>
                <div>
                  <strong>{ item.actor }</strong>
                  { item.verb }

                  {#if item.action_object_url}
                    <a href={item.action_object_url} on:click|preventDefault={() => openNotification(item)}>
                      { item.action_object }
                    </a>
                  {:else}
                    { item.action_object }
                  {/if}

                  {#if item.target}on { item.target }{/if}
                  (<TimeAgo datetime={item.timestamp} />)
                </div>
              </li>
              {/each}
            {:else}
            <span class="list-group-item p-1 text-center" v-else>There are no notifications!</span>
            {/if}
					</div>
				</ul>
    </div>
    {/if}
  </span>
{/if}
