// frontend/src/components/submit/SummaryComments.vue
<script setup>
import { ref } from 'vue';
import CommentForm from './CommentForm.vue';
import Comment from './Comment.vue';
import SuggestedComment from './SuggestedComment.vue';

defineProps({
  summaryComments: {
    type: Array,
    default: () => []
  }
});

const emit = defineEmits(['saveComment', 'setNotification', 'resolveSuggestion']);

const showForm = ref(false);

const addComment = (text) => {
  emit('saveComment', {
    text,
    success: () => {
      showForm.value = false;
    }
  });
};
</script>

<template>
  <template v-for="comment in summaryComments" :key="comment.id">
    <SuggestedComment
      v-if="comment.type === 'ai-review'"
      v-bind="comment"
      :summary="true"
      @resolve-suggestion="emit('resolveSuggestion', $event)"
    />

    <Comment
      v-else
      v-bind="comment"
      @save-comment="emit('saveComment', $event)"
      @set-notification="emit('setNotification', $event)"
    />
  </template>

  <div v-if="showForm">
    <CommentForm @save="addComment" />
  </div>

  <button v-else class="btn p-0" @click="showForm = !showForm">
    <span
      class="iconify"
      data-icon="bx:bx-comment-add"
      data-inline="false"
      data-flip="vertical"
      data-height="20"
      title="Add new comment"
    ></span>
  </button>
</template>

<style scoped>
div :global(.CodeMirror) {
  height: 100px;
}

button {
  line-height: normal;
  margin-top: -10px;
}
</style>

// frontend/src/SummaryComments.svelte
<script>
import CommentForm from './CommentForm.svelte';
import Comment from './Comment.svelte';
import { createEventDispatcher } from 'svelte';
import SuggestedComment from './SuggestedComment.svelte';

export let summaryComments;

let showForm = false;

const dispatch = createEventDispatcher();

function addComment(evt) {
  dispatch('saveComment', {
    text: evt.detail,
    success: () => (showForm = false)
  });
}
</script>

{#each summaryComments as comment}
  {#if comment.type === 'ai-review'}
    <SuggestedComment {...comment} summary={true} on:resolveSuggestion />
  {:else}
    <Comment {...comment} on:saveComment on:setNotification />
  {/if}
{/each}

{#if showForm}
  <div>
    <CommentForm on:save={addComment} />
  </div>
{:else}
  <button class="btn p-0" on:click={() => (showForm = !showForm)}>
    <span
      class="iconify"
      data-icon="bx:bx-comment-add"
      data-inline="false"
      data-flip="vertical"
      data-height="20"
      title="Add new comment"></span>
  </button>
{/if}

<style>
div :global(.CodeMirror) {
  height: 100px;
}

button {
  line-height: normal;
  margin-top: -10px;
}
</style>
