// frontend/src/SubmitSource.svelte
<script>
import { createEventDispatcher } from 'svelte';
import CodeRow from './CodeRow.svelte';
import hljs from 'highlight.js/lib/core';
export let code;
export let comments;
export let selectedRows = -1;
export let path;

let addingCommentToLine = -1;
let highlightedLines = [];

const dispatch = createEventDispatcher();

$: {
  const container = document.createElement('div');
  container.innerHTML = hljs.highlightAuto(code)['value'];

  // fix multiline comments
  container.querySelectorAll('.hljs-comment').forEach((el) => {
    if (el.innerText.indexOf('\n') >= 0) {
      let prev = el;
      for (const line of el.innerText.split('\n')) {
        const e = document.createElement('span');
        e.classList.add('hljs-comment');
        e.innerText = line;
        el.parentNode.insertBefore(e, prev.nextSibling);
        prev = el.parentNode.insertBefore(document.createTextNode('\n'), e.nextSibling);
      }
      el.remove();
    }
  });

  highlightedLines = container.innerHTML.split('\n');
}

let selecting = 0;
let userSelected = false;

function update(to) {
  let from = selecting;
  if (from > to) {
    [from, to] = [to, from];
  }

  document.location.hash = `#src;${path}:${from}${to != from ? '-' + to : ''}`;
}

function mousedown(e) {
  if (e.target.tagName == 'SPAN') {
    return;
  }
  userSelected = true;
  const td = e.target.closest('tr td:first-of-type');
  if (td) {
    selecting = td.closest('tr').rowIndex + 1;
    update(selecting);
  }
}

function mouseover(e) {
  const td = e.target.closest('tr td:first-of-type');
  if (td && selecting >= 1) {
    update(td.closest('tr').rowIndex + 1);
  }
}
</script>

<table
  on:mousedown={mousedown}
  on:mouseover={mouseover}
  on:mouseup={() => (selecting = 0)}
  data-path={path}>
  {#each highlightedLines as line, lineNumber}
    <CodeRow
      lineNumber={lineNumber + 1}
      {line}
      comments={comments[lineNumber]}
      showAddingForm={addingCommentToLine === lineNumber + 1}
      selected={selectedRows &&
        lineNumber + 1 >= selectedRows.from &&
        lineNumber + 1 <= selectedRows.to}
      scroll={selectedRows && userSelected == 0 && lineNumber + 1 == selectedRows.from}
      on:showCommentForm={(evt) => (addingCommentToLine = evt.detail)}
      on:setNotification
      on:resolveSuggestion
      on:saveComment />
  {/each}
</table>

// frontend/src/components/submit/SubmitSource.vue
<script setup>
import { computed, onMounted, ref, watch } from 'vue';
import CodeRow from './CodeRow.vue';
import hljs from 'highlight.js/lib/core';

const props = defineProps({
  code: {
    type: String,
    required: true
  },
  comments: {
    type: Object,
    default: () => ({})
  },
  selectedRows: {
    type: Object,
    default: null
  },
  path: {
    type: String,
    required: true
  }
});

const emit = defineEmits(['setNotification', 'resolveSuggestion', 'saveComment']);

const addingCommentToLine = ref(-1);
const highlightedLines = ref([]);
const selecting = ref(0);
const userSelected = ref(false);
const commentsByLine = computed(() => props.comments || {});

const updateHighlightedLines = () => {
  const container = document.createElement('div');
  container.innerHTML = hljs.highlightAuto(props.code).value;

  container.querySelectorAll('.hljs-comment').forEach((el) => {
    if (el.innerText.indexOf('\n') >= 0) {
      let prev = el;

      for (const line of el.innerText.split('\n')) {
        const e = document.createElement('span');
        e.classList.add('hljs-comment');
        e.innerText = line;
        el.parentNode.insertBefore(e, prev.nextSibling);
        prev = el.parentNode.insertBefore(document.createTextNode('\n'), e.nextSibling);
      }

      el.remove();
    }
  });

  highlightedLines.value = container.innerHTML.split('\n');
};

onMounted(updateHighlightedLines);
watch(() => props.code, updateHighlightedLines);

const updateSelection = (to) => {
  let from = selecting.value;
  if (from > to) {
    [from, to] = [to, from];
  }

  document.location.hash = `#src;${props.path}:${from}${to !== from ? '-' + to : ''}`;
};

const mousedown = (event) => {
  if (event.target.tagName === 'SPAN') {
    return;
  }

  userSelected.value = true;
  const td = event.target.closest('tr td:first-of-type');

  if (td) {
    selecting.value = td.closest('tr').rowIndex + 1;
    updateSelection(selecting.value);
  }
};

const mouseover = (event) => {
  const td = event.target.closest('tr td:first-of-type');

  if (td && selecting.value >= 1) {
    updateSelection(td.closest('tr').rowIndex + 1);
  }
};
</script>

<template>
  <table :data-path="path" @mousedown="mousedown" @mouseover="mouseover" @mouseup="selecting = 0">
    <CodeRow
      v-for="(line, index) in highlightedLines"
      :key="index"
      :line="line"
      :line-number="index + 1"
      :comments="commentsByLine[index]"
      :show-adding-form="addingCommentToLine === index + 1"
      :selected="selectedRows && index + 1 >= selectedRows.from && index + 1 <= selectedRows.to"
      :scroll="selectedRows && !userSelected && index + 1 === selectedRows.from"
      @show-comment-form="addingCommentToLine = $event"
      @set-notification="emit('setNotification', $event)"
      @resolve-suggestion="emit('resolveSuggestion', $event)"
      @save-comment="emit('saveComment', $event)"
    />
  </table>
</template>
